site_name: Matheart's Blog

nav:
    - Home:
        - index.md
    - 日常:
        - 读上交生存手册有感:
          - daily/sjtu_survival.md
        - 一点小update:
          - daily/update.md
    - 学术:
        - 泛函分析-无限维的线性代数（上）:
          - academic/func_anal1.md
        - 如何经营社交平台来获得更好的学术信息源:
          - academic/acad_media.md
    # - Computer Science: 
    #     - cs/index.md
    #     - Machine Learning:
    #       - cs/ml/index.md
    #       - Statistical Learning:
    #         - cs/ml/statml/index.md
    #       - Generalization:
    #         - cs/ml/generalization/index.md
    #       - Foundations of Machine Learning:
    #         - cs/ml/fml.md
    #     - Computer Architecture:
    #       - cs/archi/index.md
    #     - Programming Languages:
    #         - cs/pl/index.md
    #         - Rust: cs/pl/rust.md
    #         - C++: cs/pl/c++.md
    #     - Algorithms:
    #       - cs/algo/index.md
    #     - Markdown:
    #         - cs/markdown/index.md

theme: 
  name: 'material'
  language: zh
  custom_dir: overrides
  logo: assets/avatar.png
  favicon: assets/avatar.png
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    - scheme: slate

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # js/scheme.js # this is in template 'base.html'

plugins:
  - search
  #- meta
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md

copyright: Copyright &copy; 2022 - 2025 數心 (Matheart)
